[tool.poetry]
name = "vpa-prompt"
version = "1.2.0"
description = ""
authors = ["Yuvraj Singh <yuvrajsrsingh@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
